import { ArrowDown, ArrowUpRight, ArrowLeft, ShieldCheck } from "lucide-react";
import { ReceiptForm } from "./receipt-form";
import { notice } from "@/lib/notice";
export default function Home() {
  return <>
    <header className="header header-compact"><a className="wordmark" href="https://emizor.com/" aria-label="Ir al sitio principal de EMIZOR"><img src="/emizor-logo-hd.png" alt="EMIZOR — expertos en facturación" width="2170" height="725"/></a><a className="back-to-emizor" href="https://emizor.com/"><ArrowLeft size={16} aria-hidden="true"/> Volver a EMIZOR</a></header>
    <main id="inicio">
      <section className="hero"><div className="hero-inner"><div className="eyebrow">INFORMACIÓN PARA NUESTROS CLIENTES <span>LEY N.º 1733</span></div><div className="hero-grid"><div><h1>Estamos adecuando nuestra facturación<br/><em>a la Ley 1733.</em></h1><p className="hero-copy">Trabajamos en los ajustes de nuestro sistema conforme a los lineamientos del SIN. Aquí puedes conocer el estado del proceso y registrarte para recibir novedades.</p><a className="hero-link" href="#recepcion">Recibir novedades <ArrowUpRight size={18}/></a><a className="hero-secondary" href="#etapas">Ver etapas <ArrowDown size={16}/></a></div><aside className="status-card"><ShieldCheck size={34} strokeWidth={1.5}/><p className="small-title">ESTADO DE EMIZOR</p><h2>Adecuación<br/>en curso</h2><p>Nuestro compromiso es acompañarte con información clara durante la transición.</p><div className="status-foot">Actualización<br/><strong>15 de septiembre de 2026</strong></div></aside></div></div></section>
      <div className="meta-bar"><span>COMUNICADO A CLIENTES</span><span>15 SEP 2026 <span className="meta-divider">/</span> VERSIÓN 1.1</span></div>
      <section className="section process" id="etapas" aria-labelledby="process-title"><div className="section-heading"><span className="section-kicker">01 / ETAPAS DE LA ADECUACIÓN</span><h2 id="process-title">Avanzamos contigo, paso a paso.</h2><p className="process-intro">Nuestro proceso de preparación para los cambios de la Ley N.º 1733.</p></div><ol className="process-line"><li><span className="step-marker">01</span><span className="stage-label">Etapa inicial</span><h3>Revisión normativa</h3><p>Análisis de la documentación y de los requisitos técnicos del SIN.</p></li><li className="step-current" aria-current="step"><span className="step-marker">02</span><span className="step-badge">En curso</span><h3>Desarrollo de ajustes</h3><p>Adaptación del sistema de facturación a los nuevos requerimientos.</p></li><li><span className="step-marker">03</span><span className="stage-label">Pendiente</span><h3>Pruebas piloto</h3><p>Validación de los cambios en el ambiente de pruebas del SIN.</p></li><li><span className="step-marker">04</span><span className="stage-label">Pendiente</span><h3>Adecuación finalizada</h3><p>Cierre satisfactorio de las validaciones y comunicación de la disponibilidad.</p></li></ol><p className="process-note">La puesta en operación se comunicará conforme a las disposiciones aplicables del SIN.</p></section>
      <section className="content-grid section client-guidance" id="comunicado"><div className="section-label"><span>02 / PARA TU EMPRESA</span><h2>Te acompañamos<br/>en la transición.</h2></div><article className="letter">{notice.paragraphs.map((p,i)=><p key={i}>{p}</p>)}<div className="next-step"><h3>¿Qué puedes hacer ahora?</h3><p>Déjanos tus datos para recibir novedades sobre los avances y los pasos que correspondan a tu servicio.</p><p>Si tu empresa tiene una integración con EMIZOR, coordina cualquier ajuste con nuestro equipo a través de tu canal habitual de atención.</p><a href="#recepcion">Recibir novedades <ArrowUpRight size={16}/></a></div><div className="signature"><strong>Equipo EMIZOR</strong></div></article></section>
      <section className="reception-wrap" id="recepcion"><div className="section content-grid reception"><div className="section-label"><span>03 / MANTENTE INFORMADO</span><h2>Déjanos tus datos<br/>para mantenerte informado.</h2><p>Recibe novedades sobre los avances de la adecuación, las pruebas piloto y los próximos pasos para tu empresa.</p><p className="privacy">Usaremos tus datos para comunicarte novedades sobre la adecuación a la Ley N.º 1733. Puedes solicitar la actualización de tus datos o dejar de recibir estas comunicaciones a través de tu canal habitual de atención con EMIZOR.</p></div><ReceiptForm/></div></section>
      <section id="normativa" className="section content-grid"><div className="section-label"><span>04 / MARCO NORMATIVO</span><h2>Qué cambia.<br/>Qué significa.</h2><p>Referencias oficiales para entender el proceso.</p></div><div className="regulations"><div className="regulation"><span className="number">01</span><div><h3>El IVA se muestra por separado</h3><p>La Disposición Adicional Segunda de la Ley N.º 1733 modifica el artículo 5 de la Ley N.º 843: el precio neto corresponde al valor antes de impuestos y el IVA debe figurar separado en la factura.</p><a href={notice.sources.law} target="_blank" rel="noopener noreferrer">Consultar Ley N.º 1733 · SIN <ArrowUpRight size={15}/></a></div></div><div className="regulation"><span className="number">02</span><div><h3>La preparación técnica tiene su propio calendario</h3><p>La RND N.º 102600000034 establece el período del <strong>1 de octubre al 16 de noviembre de 2026</strong> para la adecuación al anexo técnico, el inicio de pruebas en ambiente piloto y la posterior autorización de sistemas.</p><a href={notice.sources.rnd} target="_blank" rel="noopener noreferrer">Consultar resolución del SIN <ArrowUpRight size={15}/></a></div></div><div className="regulation"><span className="number">03</span><div><h3>El anexo técnico está en construcción</h3><p>El portal técnico del SIN contempla cambios en documentos, formatos, datos y validaciones para el IVA Transparente. Las especificaciones pueden actualizarse durante este proceso.</p><a href={notice.sources.annex} target="_blank" rel="noopener noreferrer">Consultar anexo técnico · SIN <ArrowUpRight size={15}/></a></div></div><div className="clarification"><strong>Una diferencia importante</strong><p>El período de pruebas no equivale, por sí solo, a la entrada en vigencia del nuevo cálculo del IVA. La ley vincula esa vigencia al primer día del mes siguiente a la publicación de su decreto reglamentario. La RND mantiene el marco de facturación de la RND N.º 102100000011 hasta la publicación de la resolución que implemente los cambios.</p></div></div></section>
    </main><footer><a href="#inicio" className="wordmark"><img src="/emizor-logo-hd.png" alt="EMIZOR — expertos en facturación" width="2170" height="725"/></a><p>Información sobre la adecuación a la Ley N.º 1733<br/><span>Comunicado EMIZOR · 15 de septiembre de 2026</span></p><a href="#normativa">Fuentes oficiales <ArrowUpRight size={15}/></a></footer>
  </>;
}
