import { ArrowDown, ArrowUpRight, FileText, ShieldCheck, Settings2, MessageSquare } from "lucide-react";
import { ReceiptForm } from "./receipt-form";
import { notice } from "@/lib/notice";
export default function Home() {
  return <>
    <header className="header"><a className="wordmark" href="#inicio" aria-label="EMIZOR, inicio"><img src="/emizor-logo-hd.png" alt="EMIZOR — expertos en facturación" width="2170" height="725"/></a><nav aria-label="Navegación principal"><a href="#comunicado">Comunicado</a><a href="#normativa">Marco normativo</a><a className="nav-confirm" href="#recepcion">Recibir novedades <ArrowUpRight size={16}/></a></nav></header>
    <main id="inicio">
      <section className="hero"><div className="hero-inner"><div className="eyebrow">INFORMACIÓN PARA NUESTROS CLIENTES <span>LEY N.º 1733</span></div><div className="hero-grid"><div><h1>Nos estamos preparando.<br/><em>Te acompañamos en<br className="desktop-break"/> este cambio.</em></h1><p className="hero-copy">En EMIZOR estamos trabajando en la adecuación de nuestro sistema de facturación a los cambios de la Ley N.º 1733 y a los lineamientos del Servicio de Impuestos Nacionales.</p><a className="hero-link" href="#comunicado">Leer el comunicado <ArrowDown size={18}/></a></div><aside className="status-card"><ShieldCheck size={34} strokeWidth={1.5}/><p className="small-title">ESTADO DE EMIZOR</p><h2>Adecuación<br/>en curso</h2><p>Nuestro compromiso es acompañarte con información clara durante la transición.</p><div className="status-foot">Actualización<br/><strong>15 de septiembre de 2026</strong></div></aside></div></div></section>
      <div className="meta-bar"><span>COMUNICADO A CLIENTES</span><span>15 SEP 2026 <span className="meta-divider">/</span> VERSIÓN 1.0</span></div>
      <section className="content-grid section" id="comunicado"><div className="section-label"><span>01 / COMUNICADO</span><h2>Tu facturación,<br/>nuestra prioridad.</h2></div><article className="letter"><p className="salutation">Estimado cliente:</p>{notice.paragraphs.map((p,i)=><p key={i}>{p}</p>)}<div className="signature"><span className="signature-line"/><strong>Equipo EMIZOR</strong><span>A tu lado durante la adecuación.</span></div></article></section>
      <section className="section process" id="etapas" aria-labelledby="process-title"><div className="section-heading"><span className="section-kicker">ETAPAS DE LA ADECUACIÓN</span><h2 id="process-title">Avanzamos contigo, paso a paso.</h2><p className="process-intro">Nuestro proceso de preparación para los cambios de la Ley N.º 1733.</p></div><ol className="process-line"><li><span className="step-marker">01</span><h3>Revisión normativa</h3><p>Análisis de la documentación y de los requisitos técnicos del SIN.</p></li><li className="step-current" aria-current="step"><span className="step-marker">02</span><span className="step-badge">En curso</span><h3>Desarrollo de ajustes</h3><p>Adaptación del sistema de facturación a los nuevos requerimientos.</p></li><li><span className="step-marker">03</span><h3>Pruebas piloto</h3><p>Validación de los cambios en el ambiente de pruebas del SIN.</p></li><li><span className="step-marker">04</span><h3>Adecuación finalizada</h3><p>Cierre satisfactorio de las validaciones y comunicación de la disponibilidad.</p></li></ol><p className="process-note">La puesta en operación se comunicará conforme a las disposiciones aplicables del SIN.</p></section><section className="focus section" aria-labelledby="focus-title"><div className="section-heading"><span className="section-kicker">ALCANCE DE LA ADECUACIÓN</span><h2 id="focus-title">Una transición que requiere preparación.</h2></div><div className="focus-grid"><div><FileText/><h3>Información de la factura</h3><p>Separación del valor neto y del IVA, conforme al nuevo marco normativo.</p></div><div><Settings2/><h3>Compatibilidad técnica</h3><p>Adecuación de estructuras y validaciones según las especificaciones que publique el SIN.</p></div><div><MessageSquare/><h3>Comunicación contigo</h3><p>Información sobre avances, disponibilidad y pasos que correspondan a tu operación.</p></div></div></section>
      <section id="normativa" className="section content-grid"><div className="section-label"><span>02 / MARCO NORMATIVO</span><h2>Qué cambia.<br/>Qué significa.</h2><p>Referencias oficiales para entender el proceso.</p></div><div className="regulations"><div className="regulation"><span className="number">01</span><div><h3>El IVA se muestra por separado</h3><p>La Disposición Adicional Segunda de la Ley N.º 1733 modifica el artículo 5 de la Ley N.º 843: el precio neto corresponde al valor antes de impuestos y el IVA debe figurar separado en la factura.</p><a href={notice.sources.law} target="_blank" rel="noopener noreferrer">Consultar Ley N.º 1733 · SIN <ArrowUpRight size={15}/></a></div></div><div className="regulation"><span className="number">02</span><div><h3>La preparación técnica tiene su propio calendario</h3><p>La RND N.º 102600000034 establece el período del <strong>1 de octubre al 16 de noviembre de 2026</strong> para la adecuación al anexo técnico, el inicio de pruebas en ambiente piloto y la posterior autorización de sistemas.</p><a href={notice.sources.rnd} target="_blank" rel="noopener noreferrer">Consultar resolución del SIN <ArrowUpRight size={15}/></a></div></div><div className="regulation"><span className="number">03</span><div><h3>El anexo técnico está en construcción</h3><p>El portal técnico del SIN contempla cambios en documentos, formatos, datos y validaciones para el IVA Transparente. Las especificaciones pueden actualizarse durante este proceso.</p><a href={notice.sources.annex} target="_blank" rel="noopener noreferrer">Consultar anexo técnico · SIN <ArrowUpRight size={15}/></a></div></div><div className="clarification"><strong>Una diferencia importante</strong><p>El período de pruebas no equivale, por sí solo, a la entrada en vigencia del nuevo cálculo del IVA. La ley vincula esa vigencia al primer día del mes siguiente a la publicación de su decreto reglamentario. La RND mantiene el marco de facturación de la RND N.º 102100000011 hasta la publicación de la resolución que implemente los cambios.</p></div></div></section>
      <section className="reception-wrap" id="recepcion"><div className="section content-grid reception"><div className="section-label"><span>03 / MANTENTE INFORMADO</span><h2>Déjanos tus datos<br/>para mantenerte informado.</h2><p>Recibe novedades sobre los avances de la adecuación, las pruebas piloto y los próximos pasos para tu empresa.</p><p className="privacy">Usaremos tus datos para comunicarte novedades sobre la adecuación a la Ley N.º 1733. Puedes solicitar la actualización de tus datos o dejar de recibir estas comunicaciones a través de tu canal habitual de atención con EMIZOR.</p></div><ReceiptForm/></div></section>
    </main><footer><a href="#inicio" className="wordmark"><img src="/emizor-logo-hd.png" alt="EMIZOR — expertos en facturación" width="2170" height="725"/></a><p>Información sobre la adecuación a la Ley N.º 1733<br/><span>Comunicado EMIZOR · 15 de septiembre de 2026</span></p><a href="#normativa">Fuentes oficiales <ArrowUpRight size={15}/></a></footer>
  </>;
}
