"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { CheckCircle2, Download, ArrowUpRight } from "lucide-react";
import { notice, noticeText } from "@/lib/notice";
type Receipt = { id:string; receivedAt:string; version:string; company:string; nit:string; name:string; email:string; noticeHash:string };
export function ReceiptForm() {
  const [confirmed,setConfirmed] = useState(false);
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState("");
  const [receipt,setReceipt] = useState<Receipt|null>(null);
  const [requestId,setRequestId] = useState("");
  useEffect(()=>{setRequestId(crypto.randomUUID()); const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext; if(!ctx)return; const controller=new AbortController(); try {Promise.resolve(ctx.registerTool({name:"start_receipt_confirmation",description:"Abre el formulario de recepción del comunicado de EMIZOR. No envía ni confirma la recepción.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("No se admiten parámetros");document.getElementById("recepcion")?.scrollIntoView({behavior:"smooth"});document.getElementById("company")?.focus({preventScroll:true});return {status:"form_open",submitted:false};}},{signal:controller.signal})).catch(()=>{});}catch{} return ()=>controller.abort();},[]);
  async function submit(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); if(busy)return; setError("");
    if(!confirmed){setError("Confirma que recibiste y leíste el comunicado para continuar.");return;}
    const form=new FormData(e.currentTarget);setBusy(true);
    try {const r=await fetch("/api/recepciones",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId,version:notice.version,confirmed,company:form.get("company"),nit:form.get("nit"),name:form.get("name"),email:form.get("email")})});const body=await r.json();if(!r.ok)throw new Error(body.error||"No pudimos registrar la recepción. Intenta nuevamente.");setReceipt(body);}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar. Comprueba tu conexión e intenta de nuevo.");}finally{setBusy(false);}
  }
  function download(){if(!receipt)return;const text=`CONSTANCIA DE RECEPCIÓN — EMIZOR\n\nReferencia: ${receipt.id}\nFecha y hora (UTC): ${receipt.receivedAt}\nVersión: ${receipt.version}\nEmpresa: ${receipt.company}\nNIT declarado: ${receipt.nit}\nPersona: ${receipt.name}\nCorreo declarado: ${receipt.email}\n\nConfirmación: He recibido y leído el comunicado de EMIZOR sobre la adecuación a la Ley N.º 1733.\n\nLa identidad y representación de quien confirma son declaradas por el remitente.\nSHA-256 del comunicado: ${receipt.noticeHash}\n\nCOMUNICADO\n\n${noticeText}`;const url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`constancia-emizor-${receipt.id}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  if(receipt)return <div className="form-card success" role="status"><CheckCircle2 size={40}/><h3>Recepción registrada.</h3><p>Gracias, {receipt.name}. Guardamos tu confirmación para {receipt.company}.</p><dl><dt>Referencia</dt><dd>{receipt.id}</dd><dt>Fecha y hora</dt><dd>{new Date(receipt.receivedAt).toLocaleString("es-BO",{timeZone:"America/La_Paz"})} (Bolivia)</dd><dt>Comunicado</dt><dd>{receipt.version}</dd></dl><Button className="submit-button" onClick={download}><Download size={18}/> Descargar constancia</Button><p className="form-note">La constancia recoge los datos declarados por quien confirma.</p></div>;
  return <form className="form-card" onSubmit={submit}><h3>Confirmar recepción</h3><p className="form-intro">Completa tus datos para registrar la constancia.</p><div className="fields"><label htmlFor="company">Empresa o razón social<Input id="company" name="company" required minLength={2} maxLength={180} autoComplete="organization" placeholder="Nombre de tu empresa"/></label><label htmlFor="nit">NIT de la empresa<Input id="nit" name="nit" required pattern="[0-9]{5,20}" inputMode="numeric" maxLength={20} title="Ingresa entre 5 y 20 dígitos, sin espacios ni guiones" placeholder="Solo números"/></label><label htmlFor="name">Tu nombre completo<Input id="name" name="name" required minLength={3} maxLength={160} autoComplete="name" placeholder="Nombre y apellido"/></label><label htmlFor="email">Correo electrónico<Input id="email" name="email" type="email" required maxLength={180} autoComplete="email" placeholder="nombre@empresa.com"/></label></div><div className="consent"><Checkbox id="confirmed" checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><label htmlFor="confirmed">He recibido y leído el comunicado de EMIZOR sobre la adecuación a la Ley N.º 1733.</label></div><p className="form-note">Esta confirmación deja constancia de recepción; no modifica tu contrato ni acredita por sí sola la representación de tu empresa.</p>{error&&<p className="form-error" role="alert">{error}</p>}<Button className="submit-button" type="submit" disabled={busy||!requestId}>{busy?"Registrando recepción…":"Confirmar recepción"} {!busy&&<ArrowUpRight size={18}/>}</Button><p className="form-version">Comunicado del 15/09/2026 · Versión 1.0</p></form>;
}
